### ISSUE TITLE
help with polybar

### ISSUE THREAD

**Issue by ycf83** [deviantfero/wpgtk#109]
hi, 

thnk's for your program ,
for polybar it's always remove config, i want to know how to keep my config and change only colors , 
i use wpgtk like this:
wpg -s ~/wallpaper/wallx121.jpg

**Comment by MiltFra** [comment]
wpg overwrites the entire file from a .base version. Since the tool needs certain keywords that would cause conflict with the syntax of the file, I don't think what you ask can be achieved. Besides, what's the point? Instead of editing `~/.config/polybar/config` you should now edit `~/.config/wpg/templates/config_polybar_config.base` (or something similar). 
The problem is though that this forces you to start polybar again after you change colors. Alternatively you could use .Xresources colors in polybar, like you'd do with pywal.
Or, that's what I do, you can use a script (mine is executed when selecting an image in ranger, but that can be done in terminal as well) that sets the image and restarts polybar afterwards. This should fix the problem.
```
function set_wpg --argument file
   wpg -s $file;
   echo file > ~/.config/bg;
   sleep 1;
   wpg -s $file;
   killall polybar > /dev/null 2>&1
   polybar -r default > /dev/null 2>&1 &
end
```
Note that this is a fish function, so you might want to adapt it for your shell.
Sincerely
Franz Miltz

**Comment by ycf83** [comment]
thnk's bro, i have two polybar with module and scripte , and wpg delete all config , first time it's okay to delete config but after that  why delete all config file or i need only colors section , any why it's good programe , thnk's a lot, i backup my config file and i change only colors , by copy /past.

**Comment by deviantfero** [comment]
Hi, this is an overly complicated solution @MiltFra, please do checkout the `wpg` way, it's much much more simple.

As for @ycf83, of course you can keep your own polybar config, I'll give a detailed list of steps:

1. setup your usual polybar config as you usually do, restore your own from some backup, in fact `wpgtk` creates a backup in `~/.config/polybar/config.bak`, in case you regret your choice and want to go back to your old bar.

2. open `wpg` in your console, using the GUI navigate to the `Templates` tab, there you can choose to "add" a new template, you should now look for your polybar configuration under `~/.config/polybar/config`, this will create a template based on your own configuration file

3. (optional) alternatively, you can add your custom template to `wpg` with `wpg -xa ~/.config/polybar/config`

4. now you can edit this file from the same `Templates` tab, and you can place keywords that `wpgtk` will search and replace, such as `<COLOR0>`, `<COLOR1>`, this words will be replaced by wpgtk on each colorscheme change and automatically reload polybar.

![templatesTab](https://i.imgur.com/xSvuWom.png)

5. (optional) you can adjust the text editor that `wpgtk` opens templates with in the `Options` tab

You can find more on this subject in the projects wiki, here: https://github.com/deviantfero/wpgtk/wiki/Templates

and you can find a video tutorial on this here:
https://www.youtube.com/watch?v=QXpMMP8fT0o&t=8s
