### ISSUE TITLE
wpg not changing wallpaper

### ISSUE THREAD

**Issue by ghost** [deviantfero/wpgtk#116]
I installed wpgt in ArcoLinux Openbox but wpg dosent change the wallpaper everything else works ok!

**Comment by deviantfero** [comment]
You mentioned on an email that you had nitrogen installed, is that still the case? or do you only have feh now?

**Comment by Amanre** [comment]
I only have feh now

**Comment by deviantfero** [comment]
Hi, sorry I've taken so long to follow up, are you still having issues setting a wallpaper, did you manage to fix it?

**Comment by zoloboz** [comment]
Im having the same issue that OP has.

I have following packages installed:
feh 3.1.3-1
python-pywal 3.3.0-1
python2-pillow 6.0.0-1
python 3.7.3-1
xsettingsd 1.0.0-2
wpgtk-git r421.413248a-1
I installed wpgtk hrough the AUR so im pretty sure the dependencies are satisfied.

This is what happens when i use `wal -a wallp.jpg`:
`[i] image         Using image wallp.jpg.
[i] theme         Set theme to 
_home_zoloboz__config_wpg_wallpapers_wallp_jpg_dark_wal__1.1.0.json.  
[i] colors        Found cached colorscheme.  
[i] sequences     Set terminal colors.  
Traceback (most recent call last):  
  File "/usr/bin/wpg", line 11, in <module>  
    load_entry_point('wpgtk==6.0.6', 'console_scripts', 'wpg')()  
  File "/usr/lib/python3.7/site-packages/wpgtk/__main__.py", line 302, in main  
    process_args(args)  
  File "/usr/lib/python3.7/site-packages/wpgtk/__main__.py", line 185, in process_args  
    themer.set_theme(args.s[0], args.s[0], args.r)  
  File "/usr/lib/python3.7/site-packages/wpgtk/data/themer.py", line 41, in set_theme  
    pywal.export.every(colors, FORMAT_DIR)  
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 68, in every  
    template(colors, file.path, join(output_dir, file.name))  
  File "/usr/lib/python3.7/site-packages/pywal/export.py", line 15, in template  
    template_data = "".join(template_data).format(**colors)  
KeyError: '\n    active-background'  
`

The weird things is, that using sudo solves the problem. Thats why i thought the permissions were the problem, but i chmod 777 all my pictures and it didnt help.

**Comment by deviantfero** [comment]
yep, that error trace looks like you're dealing with a badly formatted template, but this is weird, that error trace might result from `wpg -s wallp.jpg` not simply from calling `wpg -a wallp.jpg`

`sudo` should not be making a difference here, can you check your `/home` folders permission for me?

`ls -la ~` should do the trick

**Comment by mistical2008** [comment]
I have tried to reinstall wpgtk-git package on Archlinux and all works fine.

**Comment by zoloboz** [comment]
First of all, thanks for your response, deviantfero.  
I did `ls -la ~`, do you really want the whole `/home` folder? Since i don't want to post the entire output, i can send it to you via pm.  
Here are the permissions for my Wallpaper directory:  
`drwxr-xr-x  2 zoloboz users    4096 May  8 20:05  Wallpaper`  
I'm pretty sure the permissions are fine. I also tried to put the pictures in the `/usr/share/background` directory, but that didn't help.

**Comment by zoloboz** [comment]
So, i just deleted all the templates and added them again. All of a sudden its working though (even though i tried that multiple times). Everything is work now, sick!  
I have no more questions.

**Comment by deviantfero** [comment]
hmm, no I did not want the whole   `/home` just the `.` part, they seem correct, it's still pretty weird what happened

I'm closing this issue since it seems to be resolved and the opener of the issue has not replied in a while.

thanks! enjoy using `wpgtk`
