### ISSUE TITLE
Wallpaper Folder

### ISSUE THREAD

**Issue by dustinlacewell** [deviantfero/wpgtk#119]
Is it possible to grow a new setting that allows us to specify where Wpgtk should look for wallpapers? I'm not exactly enjoying the workflow of having to explicitly "add"  and "remove" wallpapers as a seperate step from simply adding or removing wallpapers from my actual wallpaper folder.

When I was just using pywal, I just threw wallpapers I liked into a folder and they would get randomly selected. The first time a wallpaper was selected, a theme would be generated.

I use NixOS and I currently have all my pywal and app integrations configured reproducably with it. I don't need to do any manual setup to get things working on a new system. I would like to be able to just invoke wpg with a specific background directory, tell it to pick a random one, and if it has theme cached great, if not to generate one with some sensible defaults. I can always go back later and adjust the themes for a given wallpaper, or generate themes ahead of time, but there should be some possible invocation of wpg where you point it at some wallpapers and it just works.

When I say "point wpg at a directory of wallpapers" what I mean is that it doesn't then go maintain a folder of symlinks. It just uses -this- folder as the place where it looks. If I want to remove a wallpaper I just delete it from here. I don't have to delete a wpg generated symlink, or open the GUI.

Thanks for reading.

**Comment by deviantfero** [comment]
I think this is possible, but I can think of a few issues with this approach, the idea is that it does not matter which directory the file is coming from, you get the filename as the "theme" name, how would I bind other images that don't belong to that specific directory?

In `pywal` this is simple because you don't have to deal with editing color schemes, you can only set the saturation for the next color scheme to be generated IIRC, but in `wpgtk` you can choose which color scheme to edit without having to select that specific wallpaper, you can also set a wallpaper with a random color scheme.

(update wpgtk please) anyway you can try one of two things for this effect:

# thing number one
`wpg -s /path/to/dir` this will choose a file at random and set it as your current color scheme, just as pywal does, this is exactly what you're looking for, except there is a caveat

if you'd like to edit that color scheme, you'd have to follow with a `wpg -a /path/to/file`, I'll see if I can do something about this, it would be a major release tho, and I can't promise anything in the sort term.

I've updated `wpgtk` so it sets the wallpaper too when you use `wpg -s /path/to/dir` no need to -a first, but it does have the caveat mentioned above

# thing number two
`wpg -a /path/to/dir/*`, you can add a whole directory at once, this works in the GUI and CLI, in the GUI you can even multiple select various files at a time, then you can `wpg -m` for random effect.

**Comment by kleshas** [comment]
It would be nice if we could have an automatic "add all wallpapers from a specific folder, auto-balance each one, save", rather than what I'm doing right now of adding each picture, auto-balancing, saving individually. :)
Similar to what the OP requested, and i know it can be scripted from the command line, but I'm not good enough to do it myself.  iirc, windows was FOR %%F in ./ do wpg -m or something ;)

**Comment by kleshas** [comment]
Excellent, thanks :)

**Comment by deviantfero** [comment]
with `6.0.0` you can set an option to always auto-adjust new wallpapers
