### ISSUE TITLE
weird text artifacts on terminal (gnome-terminal)

### ISSUE THREAD

**Issue by websterkk** [deviantfero/wpgtk#124]
I'm getting issues similar to what was referenced in #64 when trying to apply the colorscheme without background in gnome-terminal.

When I run the command
`wpg -ns ~/.config/wpg/wallpapers/neonSpace.jpg`

The output is: 
```
[inf] image         Using image neonSpace.jpg.
[inf] theme         Set theme to _home_kjw__config_wpg_wallpapers_neonSpace_jpg_dark_wal__1.1.0.json.
[inf] colors        Found cached colorscheme.
]708;[100]#2e3440\[inf] sequences     Set terminal colors.
[inf] export        Exported all files.
[inf] export        Exported all user files.
[err] color         icons - base file does not exists
```
where #2e3440 is color0 from the theme. Obviously this isn't a problem, but that same text appears at the beginning of newly opened terminals when I have `(cat $HOME/.config/wpg/sequences &)` added to my .bashrc. The new terminal starts like this:
`
]708;[100]#2e3440\kjw@kw ~ $ ` but goes to normal when another terminal is opened. The second terminal changes to this when a third is opened.

`]708;[100]#2e3440\kjw@kw ~ $kjw@kw ~ $ `

I wasn't able to see how the answers to the previous question could fix this, am I missing something?

Thanks for all your help.

**Comment by dylanaraps** [comment]
This sequence is unsupported by VTE but unlike other terminal emulators, VTE spits it out to the user as garbage instead of simply suppressing it and doing nothing. `pywal` had a workaround for this involving escape sequence magic to suppress this output but it was removed for two reasons;

1) Newer versions of VTE hide this sequence successfully.
2) The workaround caused macOS desktops to crash.

What I can do is add a flag (`-t`) that disables this problem sequence. You'll have to use this flag every-time you run `pywal`. The other alternative (on your side) is to update your terminal version but I realize that this isn't always possible.

**Comment by dylanaraps** [comment]
@deviantfero 

I've pushed this change here: https://github.com/dylanaraps/pywal/commit/614c1ab44a8527c83ba7777d2796e4d58093186a

The option should be fully optional (so new versions of pywal work in old versions of wpgtk). Let me know if any other changes need to be made.

**Comment by deviantfero** [comment]
thanks for taking this up @dylanaraps, I've noticed this is a problem that comes up a lot, just for future reference, what's the version of VTE that fixes this bug?

I'll make sure to implement it as a configuration flag so scripts won't need a change (I'll do it when I get the chance).

**Comment by dylanaraps** [comment]
I'm pretty sure it's `Version 0.54.0`. It's a rather recent change (past 2-3 months).

**Comment by deviantfero** [comment]
@dylanaraps has re-implemented the VTE fix and I've also integrated this into `wpgtk` for those who are still having to deal with an older VTE version. I'll mark this as closed
