### ISSUE TITLE
different filesystem highlight bg color too similar to fg color

### ISSUE THREAD

**Issue by nDanielGH** [deviantfero/wpgtk#138]
I reproduce the issue as follows:
ls ~ prints the contents of my home dir as expected
ls /run/media/someNTFSfolder will show every folder with highlighted background color which is extremely similar to the foreground color. picking said bg color in gcolor will not yield a color that shows up in wpg. I have tested this with several wallpapers. perhaps a different default is in order?
Thanks.

**Comment by deviantfero** [comment]
hi, this has already been taken care of by @dylanaraps, in one of his formats, I also export it in `wpgtk`, so in order to get this benefit you should source `$HOME/.config/wpg/formats/colors.sh` somewhere in your shell configuration file, specifically this line:

`export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"`
