### ISSUE TITLE
steps for gtk-only / pywal's pre-defined themes

### ISSUE THREAD

**Issue by aleprovencio** [deviantfero/wpgtk#162]
Hello, my workflow consists on using "pure" pywal for setting colors from pre-defined themes (e.g. `wal --theme base16-solarized`) for almost all of my environment (terminal, WM, taskbar, etc) except for GTK, where I'd like to use wpgtk as a separate tool just for that, also from pre-defined themes (e.g. `wpg --theme base16-solarized`).

I've already installed the templates with `wpg-install -gi`, but wonder what are the next steps in order to achieve that in a way that wpgtk **only** change GTK colors, and not messing with the rest (e.g. terminals, WM, etc).

**Comment by deviantfero** [comment]
is there a reason for not using `wpgtk` for everything? you can just do `wpg --theme base16-solarized` and that will export everything `pywal` does in the same directories since it calls pywal in the background, including any custom template file you might have, could you elaborate why not use `wpgtk` for the other tasks as well?

**Comment by deviantfero** [comment]
Sorry I did not see this comment before, I was just checking issues to close them and I stumbled across your comment.

It's alright, though I don't understand your point, if you just want the GTK theme, why not just install the GTK theme? `wpgtk` does the exact same thing as pywal does, it won't mess with any templates that are not installed, so messing the with WMs part doesn't make much sense to me, and the sequences sent by `wpgtk` to terminals are the exact same as pywal uses, so that part confuses me too.

anyway, if you just want the GTK theme, you could just install my theme, symlink the .base files to the user templates directory for pywal (they have the same format) and then use `xsettingsd` or `xdg-settings` to reload your GTK theme afterwards.
