### ISSUE TITLE
Visual Bugs in GTK3

### ISSUE THREAD

**Issue by Frechdachs** [deviantfero/wpgtk#18]
Hey, I've encountered two problems with the GTK3 version of your theme:
### In Firefox, selected text becomes invisible if the Firefox window is active, if it's inactive the selected text becomes visible again:

Active window
![Screen](https://0x0.st/aCu.png)

Inactive window
![Screen](https://0x0.st/aCS.png)
### The scroll bar is almost invisible when not hovering or clicking it:

Neither hovered nor clicked:
![Screen](https://0x0.st/aCQ.png)

Hovering the scrollbar:
![Screen](https://0x0.st/aC1.png)

Clicking the scrollbar:
![Screen](https://0x0.st/aCj.png)

I suggest making "Neither hovered nor clicked" look the same as "Hovering the scrollbar".

BTW, I have set the environment variable `GTK_OVERLAY_SCROLLING` to `0`, disabling the stupid GTK3 feature of hiding the scrollbar.

**Comment by deviantfero** [comment]
Hi, thanks for the detailed feedback, yes it's been hard for me to fix those issues as i don't know wich widgets are causing the issue, and it's been an issue for a long time now, if you could help me pinpoint the styles that are causing this i would fix it right away, I'm using firefox with gtk2 right now because of this. 

i will fix the scrollbar issue right away! thanks

**Comment by Frechdachs** [comment]
> if you could help me pinpoint the styles that are causing this i would fix it right away

Unfortunately, I have no idea how GTK themes work.

> scrollbar issue is fixed, please reinstall with whatever method you prefer.

Much appreciated, it was annoying not to know the current position on a page or in a large directory.

**Comment by deviantfero** [comment]
I do know, but i just don't know what firefox uses, in order to go and edit that specific part of the theme, anyways, thanks for the input, i'll leave this issue open until i can get some info on what do i have to do to fix that, and well, fix it.

Thanks so much for the detailed input, I appreciate it.

but even if it was fixed, I really really would recommend you to use firefox-gtk2 if it's available to you, it's so much better.

**Comment by Frechdachs** [comment]
> i'll leave this issue open until i can get some info on what do

I will use this issue to post further problems whenever I encounter one with the GTK3 theme. This might give you a overview on what doesn't work.

### Lollypop
The seekbar at the top is not shown. (empty space between current time and total time)
The slider in the options to select the album cover size is invidible, too.
I assume both use the same slider widget.
![Screen](https://0x0.st/BOI.png)

### Pamac
The text at the bottom to indicate download progress is black-on-black.
![Screen](https://0x0.st/BOl.png)

**Comment by deviantfero** [comment]
thank you so much, i will try to adress them as fast as I can, but I'm starting my second semester tomorrow so updates may not be as frequent. Quick question, what font are you using on GTK?

**Comment by deviantfero** [comment]
Hi there, fixes for this issues are coming soon!

**Comment by deviantfero** [comment]
Hi there, the issues presented here have been all fixed, if you encounter another bug in GTK applications please let me know!

[pic1](http://i.imgur.com/IAaIP2i.png)
[pic2](http://i.imgur.com/ifG6cBi.png)
