### ISSUE TITLE
wpgtk behaving very different

### ISSUE THREAD

**Issue by icyphox** [deviantfero/wpgtk#28]
What I mean is, it doesn't work quite like what's mentioned in the README.md. So I'll list out the things I'm noticing:

* First off, my i3 config, which I added to wpgtk under Optional Files, is apparently not linked to the `config.base` file, instead a file named just `config` in the same directory. No worries, I edit that, and it works.

* Secondly, the only colors working for me are COLORIN and COLORACT. The other colors default to either of these. 

* Third, COLORACT is completely transparent. It isn't even a color. And COLORIN is the darkest color in the colorscheme. 

EDIT: I'm attaching a screenshot
![wpgtkissue](https://cloud.githubusercontent.com/assets/17672379/21590484/39807f7c-d122-11e6-9061-211a6cb18e43.png)

What you see is COLORACT, in the inactive workspace, and COLORIN in the active workspace. The text in the active WS is COLORACT.

**Comment by deviantfero** [comment]
The first point is suposed to be like that, it's linked to the file named
just config, and wpgtk reads the config.base that sits in the same
directory and replaces the config file with the colors corresponding with
the color keywords in config.base, this is so that config.base is always
the same, so basically what you have to do is.

* have both config and config.base files in that special directory, please
restore your previous config from config.bak on your i3 directory and re
add it to wpgtk, you should have all needed files again

* edit the config.base file to have words like COLORIN, COLOROUT, COLOR1,
and so on where you wish for those colors to be replaced.

* leave the config file alone

* apply a colorscheme from wpgtk, and you should see that while config.base
will remain the same, while the config file will have changed, reload your
i3 config and you should see the changes, since that config file is linked
to the original location.

On Jan 2, 2017 8:01 AM, "Anirudh Oppiliappan" <notifications@github.com>
wrote:

What I mean is, it doesn't work quite like what's mentioned in the
README.md. So I'll list out the things I'm noticing:

   -

   First off, my i3 config, which I added to wpgtk under Optional Files, is
   apparently not linked to the config.base file, instead a file named just
   config in the same directory. No worries, I edit that, and it works.
   -

   Secondly, the only colors working for me are COLORIN and COLORACT. The
   other colors default to either of these.
   -

   Third, COLORACT is completely transparent. It isn't even a color. And
   COLORIN is the darkest color in the colorscheme.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/deviantfero/wpgtk/issues/28>, or mute the thread

**Comment by Icyphox** [comment]
Okay, I now understand. But I'm still having problems. None of the colors seem to work. In fact, there is no change happening in the config files.
![wpgtkissue2](https://cloud.githubusercontent.com/assets/17672379/21599773/e459fa8e-d197-11e6-8763-c28932900cd8.png)

On the right is my `config.base` and on the left is my actual config file. There is no change happening.

**Comment by deviantfero** [comment]
please do the following

```
ls -l ~/.config/i3/
```

apply a colorscheme from wpgtk and show the same two files again.

attaching a screenshot of my machine and results:
![image](http://i.imgur.com/DtL9xj7.png)

after applying wpgtk another time.
![image](http://i.imgur.com/lG4pWwG.png)

**Comment by Icyphox** [comment]
Actually, everything works fine  now :D 
All I did was uninstall, and reinstall. Thanks anyway :)
And I love it, it's just great.
