### ISSUE TITLE
feature request: support different types of color generation

### ISSUE THREAD

**Issue by neeasade** [deviantfero/wpgtk#3]
it would be cool if there were a dropdown that could 'outsource' initial color pallet generated to different scripts, such as:
- https://github.com/nixers-projects/urnn
- https://github.com/thefryscorer/schemer2

**Comment by deviantfero** [comment]
sounds great, but i think i'd still would generate the colorscheme with wp regardless of the method I choose and then apply the other scripts in order to keep consistency in the ~/.wallpapers/ folder, also it would need a method to generate an image from those scripts to show as a "sample" or preview, I think it is completly possible. 

I think urnn is a better candidate for this task, as it outputs a file and needs no modifying to be implemented. I will most likely work on it in a week or two, but i will make a different branch for it.

also, a "feature" i always forget to mention is that it always generates different colorschemes from an image, let's say you don't like one colorscheme, just remove the image and re-add it, it may give you the result you're looking for.

I will keep this issue open until I implement it.

**Comment by deviantfero** [comment]
I have changed the color generation engine to `wal` and I'm going to be collaborating with it's developer from now on.
