### ISSUE TITLE
Migrate to pywal

### ISSUE THREAD

**Issue by boardfish** [deviantfero/wpgtk#36]
`wal` is deprecated now, so a migration to `pywal` seems to be in order... Thankfully, it runs on Python too, so that helps, but there are some changes, such as color files now being in .json format.

**Comment by omrisim210** [comment]
From what I see wpgtk executes wal as a shell command, but if @deviantfero  or anyone else with enough python knowledge (maybe me?) could migrate it to the actual `pywal` API that would be awesome.

Although I'm afraid there is some duplicate functionality between the two tools. `pywal` exports some files and I have scripts for parsing those files and coloring my programs, but wpgtk also has a mechanism for external config files. I think wpgtk needs to be refactored to use as much as possible from pywal and create the best program possible but it will take some amount of work and require being familiar with both programs

**Comment by deviantfero** [comment]
As of right now I can't think of any duplicate functionality that `pywal` and `wpgtk` might have, some things like optional files are done in wpgtk because they're handled differently allowing for more flexibility, as they allow any text file to be processed by it. Like you were saying `pywal` needs scripts in order to do that, whereas `wpgtk` tries to provide an easier alternative via a user interface that replaces keywords in a .base file (the choice is always yours, of course and I might change it in the future to accomodate pywal's API), the migration will come definetly, I've been talking with `pywal`'s author about it. I just need to have time to get familiar with `pywal`. I've made a branch for this issue alreade `PR-36` I think.

**Comment by omrisim210** [comment]
@deviantfero Thanks a lot for all the work you put into this, these two projects on my "can't wait to see how it'll turn out to be" list (together with AMD's open source drivers and a few other things 😃)

**Comment by deviantfero** [comment]
@omrisim210 I'm flattered by your comment, I will put hard work into it, I'm still in college though so my schedule might not be the best, but I'll continue to develop this little frontend for wal proyect and to improve it the best way I can.

**Comment by undying-fish** [comment]
Yeah, I'm definitely looking forward to the extra power you can bring to `wal` with this. Thankfully there are some tweaks that may make your life a lot easier, such as the fact that schemas are now JSON.

**Comment by dylanaraps** [comment]
I've started work on a proper api for `pywal`. This should make it much easier to integrate with `wpgtk`.  It's still very basic and there's a lot to do before it hits master. I'd like some feedback or ideas as to what I should expose to the api to make things as easy as possible for you guys. :)

Here's an early example script: https://github.com/dylanaraps/pywal/blob/api/examples/example.py

You can follow progress here: https://github.com/dylanaraps/pywal/pull/52

**Comment by deviantfero** [comment]
I've started migration to pywall's API, and you can also follow progress here: [deviantfero/wpgtk#38](https://github.com/deviantfero/wpgtk/pull/38)

**Comment by deviantfero** [comment]
The pywal API has been integrated.
