### ISSUE TITLE
Wpg doesn't work in cron job

### ISSUE THREAD

**Issue by ranfdev** [deviantfero/wpgtk#40]
In my crontab i have this:
```
* * * * * ~/scripts/nightmode.sh > test
```
and in my ```nightmode.sh```:
```wpg -s material27night.png```.

Expected: it should change the wallpaper and the color scheme.
the command should return the following in the terminal: 
```
cdcd2e
83831e
6a6a18
INF::FG: cdcd2e
INF::BG: 83831e
030303
OK::OPENBOX
ERR::NO OPENBOX INSTALL!
ERR::TINT2 - BASE FILE DOES NOT EXIST
050505
OK::GTK2
030303
OK::GTK3
OK::GTK3.20
OK::ICONS
INF::CURRENT GLYPH: 563709
OK::OPTIONAL FILES - i3.config
OK::OPTIONAL FILES - rofi.config
OK::OPTIONAL FILES - lollo.conkyrc
OK::FINISHED
cp: '/home/lollo/.wallpapers/material27night.png'ers/material27night.png' are the same file
colors: Generated colorscheme
colors: Set terminal colors
wallpaper: Set new wallpaper
export: Exported escape sequences
export: Exported scss color variables
export: Exported sh color
```
What's really happening: nothing happens. In the file ```test``` i get:
```
b17213
72490c
563709
INF::FG: b17213
INF::BG: 72490c
030303
OK::OPENBOX
050505
OK::GTK2
030303
OK::GTK3
OK::GTK3.20
OK::ICONS
INF::CURRENT GLYPH: 080808
OK::OPTIONAL FILES - i3.config
OK::OPTIONAL FILES - rofi.config
OK::OPTIONAL FILES - lollo.conkyrc
OK::FINISHED
```

**Comment by deviantfero** [comment]
I think the output differences are due to you not doing 2>&1, this means you are only redirecting the stdout and not the stderr, you can read more about this here: https://stackoverflow.com/questions/818255/in-the-shell-what-does-21-mean

on the other hand, the wallpaper should at least change, your logs seem to be fine, aside from that fact, did you install via the AUR or did you clone the repository?

still, nothing seems to be wrong here. I need you to post some things so I can maybe help you out.

* the output of `ls -a ~/.wallpapers/`
* what's your wallpaper software? feh is there any other ?
* what's your terminal?
* did you reload your respective config files after cron ran?

**Comment by ranfdev** [comment]
I installed wpg by cloning the repo.
I tried reinstalling it, deleting the folder ./wallpepers and readding the wallpaper, but i get the same behaviour. 
The output of ```ls -a .wallpapers/``` is:
```
.   cache     material27night.png  sample    wp_init.sh
..  .current  material27.png       wpg.conf  xres
```
I set the wallpaper using wp_init.
I'm using urxvt as the terminal.
I don't reload any config file. When i run ```wpg``` from the terminal it just works

**Comment by deviantfero** [comment]
what is your wallpaper software? feh? 
do you get the new coloscheme in your terminal?

and I'm sorry about this, what I really needed was `ls -al ~/.wallpapers`

**Comment by ranfdev** [comment]
Tomorrow i'll try it out. I don't use feh or any other wallpaper software. I use wpgtk to set the colorscheme and also the wallpaper.

_Sent from my ZUK Z2 Plus using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by deviantfero** [comment]
That's the detail, `wpgtk` relies on other tools such as `feh` to set the wallpaper, please install `feh` and try again.

**Comment by ranfdev** [comment]
feh is already installed. It should not be a problem related to the cron paths because i also tried calling wpg from the absloute path: ```/usr/local/bin/wpg```.

**Comment by deviantfero** [comment]
another detail, internally `wpgtk` uses a script called `wal` to set and change terminal colors and wallpapers, which also resides in `/usr/local/bin` so you should try the path solution since you can't call it from the absolute path, that should be the issue, if this doesn't work please let me know, as I will set up a virtual machine and try to reproduce this bug, I'm fairly certain that should be the issue.

**Comment by ranfdev** [comment]
I typed ```env``` in my terminal to see all the contents of ```PATH=....```.
I copied every path variable and added it to the crontab... Still nothing...

**Comment by ranfdev** [comment]
I solved the issue! Once you told me it uses feh, I searched for problems related to feh. 
The solution --> add ```DISPLAY=:0``` before the ```wpg``` command.

Motivation: cron doesn't have the DISPLAY variable, you must manually provide it.

Source: https://bbs.archlinux.org/viewtopic.php?id=54659
