### ISSUE TITLE
Error when running WPG command

### ISSUE THREAD

**Issue by rushsteve1** [deviantfero/wpgtk#5]
Whenever I run the `wpg` command I get the following output:
![2016-03-14-125503_1366x768_scrot](https://cloud.githubusercontent.com/assets/5970439/13752382/da9185ee-e9e4-11e5-87d7-26b36e0c2c24.png)

OS: Debian Testing
WM: Openbox

**Comment by deviantfero** [comment]
Why are you using the sudo command?

**Comment by rushsteve1** [comment]
The reason I used sudo was because if i didn't i would get an immediate `permission denied` and wouldn't even get an error.
However I did learn something useful. An at least temporary solution is setting that index value to 3. Seriously. At one point when troubleshooting my desktop I got this error and, out of frustration, tried it and wpgtk launched.
Now I have no idea what that list is trying to do, or what that index even relates to, but maybe knowing that will help.

**Comment by deviantfero** [comment]
If it helps, it takes out the filename out of a dynamic link called ".current" wich points to your current wallpaper image, so it is displayed when you open wpgtk but since you execute the script at sudo, there's no ~/.wallpaper folder to check, and the list is not filled until index 4. you are having trouble with permissions? I would recommend installing again, overwriting the files (not necessary to uninstall, just clone again and run bash ./installcolor.sh ), you might have missed a password in the prompt or something, i've installed it in several debian systems without having this issue, please let me know if re-installing works for you.

**Comment by rushsteve1** [comment]
I figured it out. The src and py folders in /usr/local/bin cannot be access by the user. Seems to happen when you cp them in. This can be fixed by adding two lines to the installcolor.sh script:
`sudo chmod ugo+rx py`
`sudo chmod ugo+rx src`

**Comment by deviantfero** [comment]
Thanks for the fix @rushsteve1 !
