### ISSUE TITLE
What's the proper way to setup a Xresources.base file?

### ISSUE THREAD

**Issue by dumpsters** [deviantfero/wpgtk#77]
I created a link in ~/.themes/color_other to my $HOME/.Xresources file and created a .Xresources.base where I use things like
`URxvt.background: [95]#COLOR0`
and the rest of my URxvt-related stuff
My .xinitrc has the usual
```
if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi
```
and my WM startup has
`bash ~/.wallpapers/wp_init.sh`

When using the wpgtk GUI it won't apply immediately the changes to any open terminals which is a shame but it does generate and replace my $HOME/.Xresources correctly. That being said some properties still get overritten by something, I'm assuming it's current.Xres or something like that.
For instance not only transparency won't work but the foreground color is overritten when restoring on DE/WM start with:
`bash ~/.wallpapers/wp_init.sh`
Is this the proper way to do this or I'm supposed to just use the wp.init.sh, forget the Xresources.base and edit the theme files manually to add transparency after each "Set" in the GUI?

**Comment by deviantfero** [comment]
you should try using the `Options` tab, and then do a `xrdb -merge ~/.Xresources` after each set, that should do the trick. do as in the following pic.

![settings](https://i.imgur.com/m89Fjzb.png)

then click on save, this should execute a merge with your updated .Xresources everytime a theme is set or restored, even from cli and with the wp_init.sh script  too!

this will ensure your latest merged .Xresources is the one with the latest values.

* Since transparency can't be sent via sequences it won't update immediatly as with the other colors which  are sent via sequences to terminals, but when you open a new terminal it should have the transparency you're looking for.

* To avoid the override of the foreground color, specify your foreground color in the .Xresources file, it will still be overriden via pywal's sequence, but in new terminals it should have the one you specified.

hope this clears some things up
