### ISSUE TITLE
Make Custom Keywords value switch with Wallpaper

### ISSUE THREAD

**Issue by domsch1988** [deviantfero/wpgtk#78]
I love the new custom keyword feature. It opens up a whole new level of customization. What i thought would work, but doesn't, is that the value changes based on theme.

Lets say i use i3. I define a keyword for border size (or font). Now i want that to depend on the selected theme. With some wallpapers i'd like 5px border and Menlo as Font, with others no border and Inconsolata. You get the idea.
Currently i have to manually change that whenever i change theme.

**Comment by deviantfero** [comment]
I can think of a way to achieve this, but it's scrapping the feature and do it from the ground up, it could generate a file with keywords per wallpaper as with the colorscheme, and as with the color tab, you would select the wallpaper and the keywords would change.

I don't think I'll implement this for a while since it just got out (and it's in the new config file too), I will definetly look into this in the future, so I'll keep the issue open, right now I'm starting to work on improving the color picker on the color tab, you'll be able to edit colors via their hue, lightness and saturation.

**Comment by deviantfero** [comment]
@domsch1988 this has been requested once again on #213, I'm already working on this, I'll close this issue, refer to the new one for updates on this
