### ISSUE TITLE
Polybar missing text/background color when logging off/restarting

### ISSUE THREAD

**Issue by ev-wilt** [deviantfero/wpgtk#81]
When running wpgtk, if I set my color scheme, polybar will update properly and show all text, colors, etc. However, when I log out of i3 or otherwise restart my laptop polybar looks like [this.](https://imgur.com/ruv9AIx) It's missing the background color as well as any text. If I run wpgtk upon startup it fixes the issue. I'm using the polybar template given in the wpg-install.sh file.

Also, in my i3 config I have `exec_always --no-startup-id $HOME/.config/polybar/launch.sh` and launch.sh look like [this.](https://pastebin.com/sC60KYTf)

**Comment by deviantfero** [comment]
Hi, are you executing `~/.config/wpg/wpg-init.sh` on startup before loading polybar?

**Comment by ev-wilt** [comment]
Yes. I have this in my i3 config: `exec --no-startup-id ~/.config/wpg/wp_init.sh `

Also, I noticed restarting i3 also seems to resolve the issue.

**Comment by deviantfero** [comment]
I found the reason, the colors defined as `${xrdb:colory}` have no fallback and thus fail to load on startup since no .Xresources has been merged, I will fix this in the next iteration of the template, but for now you can edit out all `${xrdb:colory}` for `#COLORY or #COLORXYY`, if you have no `xrdb` references it should start up just fine

**Comment by ev-wilt** [comment]
Awesome. Thank you!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by deviantfero** [comment]
this has been fixed, you can now update your polybar template if you'd like, note that i've made some small changes to it, but I think is for the best.
