### ISSUE TITLE
wpgtk is not setting my wallpaper

### ISSUE THREAD

**Issue by leggettc13** [deviantfero/wpgtk#83]
I am using wpgtk with xfce and i3 as a window manager. The colors of UI elements change appropriately to match the selected Wallpaper, but the wallpaper itself is not set as my background. I have nitrogen installed, and can change the wallpaper with nitrogen, so why is the wallpaper not being set? Doesn't wpgtk use nitrogen if you have it installed? Interestingly, I can't set the desktop background any other way, such as through XFCE's inbuilt desktop background selector. Could it be that wpgtk is trying to use that? If so, how can I make it use nitrogen instead?

**Comment by deviantfero** [comment]
Hi could you post a log of `wpgtk` when you run it from console? do you have `feh` installed (this might conflict with nitrogen to set the wallpaper)?

**Comment by leggettc13** [comment]
I do not currently have feh installed, but I did when I first compiled wpgtk. Could that be causing the issue? I'll post a log of wpgtk in a moment.

**Comment by leggettc13** [comment]
[wpg.log](https://github.com/deviantfero/wpgtk/files/1709814/wpg.log)

**Comment by deviantfero** [comment]
There's nothing out of the ordinary with the log, could you try uninstalling nitrogen and try to set a wallpaper with `wpgtk`? I think that would work just fine, but if you still want to use nitrogen, read the reason bellow and the solution too.

Because you use xfce4 it tries to set the wallpaper with `xfconf` and ignores nitrogen, if you still want to use `nitrogen` I would recommend taking a look at this issue https://github.com/deviantfero/wpgtk/issues/74 more specifically, the way he calls a script to set the wallpaper with nitrogen after `wpgtk` makes the changes, if you need more help please do say so. I'll keep this issue open til you resolve on your side.

**Comment by leggettc13** [comment]
Thank you, that works. xfconf seems to not be working for some reason (probably as a result of installing i3 and using it instead of xfwm and xfdesktop) so nitrogen was a must for me. With a bit of tweaking, the scripts work for me.

While I'm here, I noticed that a lot of the scripts referenced a .wallpapers directory, that wasn't created on my system. Instead, my wallpapers are in .config/wpg/wallpapers. Is that just a folder they created to store their wallpapers or was that supposed to be created when installing wpgtk?

**Comment by deviantfero** [comment]
Sorry for not answering earlier, it was because up until recently most things `wpg` related where under `$HOME/.wallpapers` and it was honestly a really dirty way to store things in the user's `$HOME`, so in more recent versions all things have been moved to a specific `$HOME/.config/wpg` folder as in the version you have currently installed, you can read more about this changes here https://github.com/deviantfero/wpgtk/pull/76

glad you found a way to use nitrogen, I'm closing this issue.
