### ISSUE TITLE
polybar not updating correctly

### ISSUE THREAD

**Issue by AUTplayed** [deviantfero/wpgtk#97]
Not sure if it's only with polybar, but the colors aren't updating.

Quick look inside my polybar config:
```
[colors]
background = ${xrdb:color0}
foreground = ${xrdb:color7}
foreground-alt = ${xrdb:color7}
primary = ${xrdb:color1}
secondary = ${xrdb:color2}
alert = ${xrdb:color3}

[bar/bar]
background = ${colors.background}
foreground = ${colors.foreground}
```
as you can see I'm using the xresources colors.

I have `wal`  selected as my backend in wpgtk.

Now if I set a colorscheme with wpg, it sets my polybar colors to a specific colorscheme, but not the one selected. Example: 

The underline of my i3 workspace view is color1, ![i3](https://i.imgur.com/GXRjxOI.png
)  ![wpgtk](https://i.imgur.com/KGhjqQa.png
) 
but as you can see, red isn't even in the colorscheme.

Now here comes the weird part, if I just autogenerate a theme with plain old `pywal` using `wal -i <picture>` then it does change my polybar colors. And if I now try to change the colorscheme with wpgtk again, it resets to the red one.

[Here's a video](https://i.imgur.com/Yp3mfTT.mp4)

**Comment by deviantfero** [comment]
Hi, thanks for opening this issue, I have two requests, could you open `wpg` from console, and show me the output, also, what happens if you manually restart pywal after applying the theme? Is this behaviour consistent?

### possible cause

`wpgtk` merges your user defined `.Xresources` to avoid overriding colors defined by yourself in that file, so maybe you have colors defined in that file, the flow goes:

`theme.Xres applied -> .Xresources applied`, that way if you want a custom background for your applications you can set it there to override the theme's background.

So i'd like to see your `.Xresources` too, if you have colors defined there, that's the source of the issue, try commenting those colors, and try again. Please let me know how it goes

**Comment by AUTplayed** [comment]
hi, thanks for your response.

It seems like you're right, in my .Xresources I have tons of color definitions.
The console output also suggests that:

```
[inf] image         Using image <img>
[inf] colors        Found cached colorscheme.
[inf] sequences     Set terminal colors.
[err] color         icons - base file does not exists
[inf] wallpaper     Set the new wallpaper.
[inf] export        Exported css.
[inf] export        Exported shell.
[inf] export        Exported xresources.
xrdb:  "XTerm*background" on line 211 overrides entry on line 34
xrdb:  "XTerm*foreground" on line 212 overrides entry on line 35
xrdb:  "XTerm*faceName" on line 214 overrides entry on line 37
```

I removed the color definitions from my .Xresources and now it works perfectly fine!
Thanks
